import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}

import React from "react";

type Props = {};

const Nav = (props: Props) => {
  return (
    <div className="p-5 w-full bg-slate-500 text-slate-50 flex items-center justify-evenly">
      <Link href="/">Home</Link>
      <Link href="/users">Users</Link>
    </div>
  );
};
